name: MythicInventories
version: '${version}'
main: dev.heypr.mythicinventories.MythicInventories
author: heypr
api-version: '1.20'
softdepend:
  - MythicMobs
commands:
  mythicinventoryopen:
    description: Open a MythicInventory
    usage: /mythicinventoryopen <inventory>
    permission: mythicinventories.open
    aliases:
      - mio
      - miopen
      - mythicio
  mythicinventoryreload:
    description: Reload MythicInventories
    usage: /mythicinventoryreload
    permission: mythicinventories.reload
    aliases:
      - mir
      - mireload
      - mythicireload
  migrateolddata:
    description: Migrate old player data
    usage: /migrateolddata
    permission: mythicinventories.migrate
    aliases:
      - migrateold
      - migrate
